name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$TEST_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H serverbuilding.com >> ~/.ssh/known_hosts

      - name: Deploy code
        run: |
          ssh yoshihiro@serverbuilding.com 'cd /var/www/html && git pull origin main'
